from flask import Flask
from .api import api
from .db import create_db

app = Flask(__name__)

@app.errorhandler(404)
def page_not_found(error):
    """Return generic 404 page"""
    return 'Requested page does not exist', 404

# Register the API Blueprint to the Flask API
# TODO: have multiple blueprints for each part of the API?
app.register_blueprint(api)

# set the flask secret key to the same one generated by the API blueprint
app.secret_key = api.secret_key

# set the SQLAlchemy database stuff for the flask app
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///server.db'
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

# once the flask app has been initialized, set up the DB
create_db(app)